version: '3'
services:
  apollo:
    container_name: apollo-node
    build: .
    volumes:
      - .:/usr/app
    ports:
      - 4003:4003
      - 3000:3000
    depends_on:
      - db
  db:
    container_name: graphql_postgres
    image: postgres
    restart: always
    volumes:
      - ~/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgresql_knex
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

volumes:
  pgdata: ~
